name: self-hosted-action-runner
on: push
jobs:
  Ubuntu-ARM64:
    runs-on:
      [self-hosted, ubuntu-22.04, ARM64]
    steps:
      - name: ubuntu-latest-arm64
        run: |
          echo "ubuntu-latest arm64"
          lsb_release -a
          lscpu

  Ubuntu-ARM64-GPU:
    runs-on:
      [self-hosted, ubuntu-22.04, ARM64]
    steps:
      - name: ubuntu-latest-arm64-gpu
        run: |
          echo "ubuntu-latest arm64"
          lsb_release -a
          lscpu
          lshw -C display
          lspci | grep ' VGA ' | cut -d" " -f 1 | xargs -i lspci -v -s {}
